defaults:
  - general: common
  - logbook: common
  - experiment: cifar10
  - dataset: cifar10
  - model: resnet18
  - optim: adam

hydra:
  job_logging:
    root:
      handlers: []
  run:
    dir: outputs/${general.id}/${now:%Y-%m-%d_%H-%M-%S}