general:
  seed: 42
  base_path: /private/home/${env:USER}/projects/torch-template
  device: cuda:0
  id: sample_config
  description: Sample Config
  tags:
    - sample
  commit_id:
  date:
  slurm_id:

logbook:
  dir: ${general.base_path}/logs/${general.id}
  logger_file_path: ${logbook.dir}/log.jsonl
  tensorboard:
    logdir: ${logbook.dir}/tb

experiment:
  num_epochs: 100
  persist_frequency: -1 # If persist frequency < 0, the model is not persisted
  persist_best_model: False
  early_stopping_patience: 100
  save_dir: ${general.base_path}/models/${general.id}
  load_path: ${general.base_path}/models/7/best_model.tar"
  should_load_model: false
  modes:
    train:
      frequency: 1
    validation:
      frequency: 1

dataset:
  _load: dataset/cifar10

model:
  cls: codes.model.${dataset.name}_resnet.ResNet18

optim:
  # cls should be the Optimizer class
  # Other key-word arguments are passed to the optimizer constructor
  cls: torch.optim.Adam
  lr: 0.001

scheduler:
